### ISSUE TITLE
cfg file problem for different SDK version

### ISSUE THREAD

**Issue by coolcat647** [ibcn-cloudlet/ti_mmwave_rospkg#1]
Hardware: AWR1443boost ES3.0
OS: Ubuntu 16.04
Software:
- UniFlash 4.6.0
- SDK version: 1.02, 2.00 (cannot work)
- SDK version: 2.01  (use xwr14xx_mmw_demo.bin)
- mmwave_industrial_toolbox_3_1_1
- mmWave Demo Visualizer

I tried to follow the [ROS setup guide](http://dev.ti.com/tirex/content/mmwave_training_1_6_1/labs/lab0006-ros-driver/lab0006_ros_driver_pjt/TI_mmWave_ROS_Driver_Setup_Guide.pdf) to burn the firmware into my board with SDK1.02 and launch the ROS node. I got failed message:"Aborting flashing of specified files!!!" when pressing "load" button in Uniflash. 
After seeing this [flashing device problem](https://e2e.ti.com/support/sensors/f/1023/t/748929?tisearch=e2e-sitesearch&keymatch=RADAR) and keeying trying, I found that I only need to burn with  one file in SDK2.01(as mentioned above). It is different from the ROS_setup_guide...

Then I tried to launch ROS node in this repo, Got failed message:
```
[ INFO] [1548867538.572997576]: mmWaveQuickConfig: Sending command: 'sensorStop'
[ INFO] [1548867538.574653579]: mmWaveCommSrv: Sending command to sensor: 'sensorStop'
[ INFO] [1548867539.574696657]: mmWaveCommSrv: Received response from sensor: ''
[ INFO] [1548867539.575788204]: mmWaveQuickConfig: Command failed (mmWave sensor did not respond with 'Done')
[ INFO] [1548867539.575824576]: mmWaveQuickConfig: Response: ''
[ INFO] [1548867539.577424209]: mmWaveCommSrv: Sending command to sensor: 'sensorStop'
[ INFO] [1548867540.577512224]: mmWaveCommSrv: Received response from sensor: ''
[ERROR] [1548867540.578420967]: mmWaveQuickConfig: Command failed (mmWave sensor did not respond with 'Done')
[ERROR] [1548867540.578455006]: mmWaveQuickConfig: Response: ''
```

 and found the cue "Created for SDK ver:01.01" in cfg file...
I got the same error and found that message "Created for SDK ver:01.02" when I used the lab0006-ros-driver in [mmwave_industrial_toolbox_3_1_1](http://dev.ti.com/tirex/#/?link=Software%2FmmWave%20Sensors%2FIndustrial%20Toolbox)

I tried to use [mmWave Demo Visualizer](https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/3.1.0/) and compare each command you send to the AWR1443. Finally I got success when I add "lowPower" command in lab0006-ros-driver 1443_3d.cfg file, but It's not stable solution because I got the same error as above sometimes and I need to press reset button on the board.

I hope that TI create the update for this repo and "correct step for burning firmware and launching ROS node in different version of hardware such as ES1.0-3.0" 

Thank you

**Comment by tverbele** [comment]
This repo was just for our internal research projects and is not backed or linked at all to official TI repositories. This will probably not work on other SDK versions or board revisions than the one we used.

**Comment by aredman** [comment]
The chirp configuration files that are included with the repo in the cfg folder are made for mmWave SDK version 1.1. You will need to match the version number in these files with the version of the SDK on your radar sensor. Either flash your radar sensor with the old version of the SDK, or update these files using the mmWave Demo Visualizer. Make sure that you are outputting a scatter plot. Also note that you will need to manually disable range/doppler grouping if you don't want those features.
